(package "cogru"
         "0.1.0"
         "Cogru plugin for real-time collaborative editing")

(website-url "https://github.com/Cogru/cogru.el")
(keywords "convenience" "cogru")

(package-file "cogru.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
